[project]
version = 1
win_targets = [
    { platform = 'Authoring', architectures = ['x64'], toolset = 'vc160' },
    { platform = 'Windows_vc160', architectures = ['x64'] },
#    { platform = 'Android', architectures = ['arm64-v8a', 'armeabi-v7a'] },
]
mac_targets = [
#    { platform = 'Authoring', architectures = ['universal'] },
    { platform = 'iOS', architectures = ['iOS'] },
]

[plugin_info]
MenuPath = 'custom'

[plugin_info.platform_support.Any]
CanBeInsertOnBusses = true
CanBeInsertOnAudioObjects = true
CanBeRendered = true


[parameters.defines.amount]
type = 'uint'
rtpc_type = 'Exclusive'
default_value = 0
min_value = 0
max_value = 64
description = [
    { language = 'en', text = 'Adjusts how pronounced the effect is by increasing the order of the all-pass filter' },
    { language = 'zh', text = '通过增加全通滤波器的阶数来调整效果的明显程度' }
]

[parameters.defines.frequency]
type = 'float'
rtpc_type = 'Exclusive'
default_value = 600
min_value = 20
max_value = 20000
description = [
    { language = 'en', text = 'The frequency of the filter' },
    { language = 'zh', text = '滤波器的频率' }
]
user_interface = 'SliderType="4"'

[parameters.defines.pinch]
type = 'float'
rtpc_type = 'Exclusive'
default_value = 0.3
min_value = 0.01
max_value = 10
description = [
    { language = 'en', text = 'The Q setting of the filter, which will have the effect of concentrating the delay around the frequency' },
    { language = 'zh', text = '滤波器的Q值，它将会使延迟集中在频率附近' }
]
